### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by kamov** [PHP-FFMpeg/PHP-FFMpeg-Extras#5]
Hi,
I get below error when trying to install via composer:

    - The requested package php-ffmpeg/php-ffmpeg-extras could not be found in any version, there may be a typo in the package name.

But sure how to load this.

my composer is:

{
    "require": {
        "php-ffmpeg/php-ffmpeg": "0.6.1",
        "php-ffmpeg/php-ffmpeg-extras": "0.3.1"
    }
}

**Comment by patkar** [comment]
The package name is `php-ffmpeg/extras`
